In [13]:
import numpy as np

list1 = [1,2,3,4,5,6]
arraylist1 = np.array(list1)           #Создание массива из списка
print("Массив из списка:", arraylist1)
print()

matrix_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])     #Создание двумерного массива из списка
print("Двумерный массив:")                 
print(matrix_2d)
print()

arrayzeros = np.zeros(10)                   #Создание массива функцией zeros
print("Массив из нулей:", arrayzeros)
print()

arrayones = np.ones(10)                     #Создание массива функцией ones
print("Массив из единиц:", arrayones)
print()

arrayarrange = np.arange(0, 20, 2)          #Создание массива методом arrange
print("Массив методом arange:", arrayarrange)
print()

atributearray = np.array([[1,2,3], [4,5,6]], dtype=np.float64)   #Создание демонстрацонного массива

print("Массив для примера:")
print(atributearray)                               
print("Форма массива:", atributearray.shape)        #Вывод атрибутов массива
print("Тип данных массива:", atributearray.dtype)
print()

array2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

print("Исходный массив:")
print(array2d)

print("Получение отдельных элементов:")
print("array2d[0, 1] =", array_2d[0, 1])      #Первая строка, второй столбец
print("array2d[2, 3] =", array_2d[2, 3])      #Третья строка, четвертый столбец
print()


print("Извлечение подмассивов:")               #Извлечение подмассива с помощью среза

print("Срез [1:, :2]:")
print(array_2d[1:, :2])                        # Со второй строки до конца, первые два столбца
print()


arr1 = np.array([1, 2, 3, 4, 5])               #Создание массивов ля операций
arr2 = np.array([10, 20, 30, 40, 50])

print("arr1 =", arr1)
print("arr2 =", arr2)
print()

print("arr1 + arr2 =", arr1 + arr2)            # Поэлементное сложение
print("arr1 * arr2 =", arr1 * arr2)            # Поэлементное умножение
print("arr2 - arr1 =", arr2 - arr1)            # Поэлементное вычитание
print("arr2 / arr1 =", arr2 / arr1)            # Поэлементное деление
print()

print("Базовые статистики для arr1:")
print("Среднее значение (mean):", np.mean(arr1))
print("Сумма всех элементов (sum):", np.sum(arr1))
print("Минимальное значение (min):", np.min(arr1))
print("Максимальное значение (max):", np.max(arr1))

Массив из списка: [1 2 3 4 5 6]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Массив из нулей: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Массив из единиц: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Массив методом arange: [ 0  2  4  6  8 10 12 14 16 18]

Массив для примера:
[[1. 2. 3.]
 [4. 5. 6.]]
Форма массива: (2, 3)
Тип данных массива: float64

Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Получение отдельных элементов:
array2d[0, 1] = 20
array2d[2, 3] = 120

Извлечение подмассивов:
Срез [1:, :2]:
[[ 50  60]
 [ 90 100]]

arr1 = [1 2 3 4 5]
arr2 = [10 20 30 40 50]

arr1 + arr2 = [11 22 33 44 55]
arr1 * arr2 = [ 10  40  90 160 250]
arr2 - arr1 = [ 9 18 27 36 45]
arr2 / arr1 = [10. 10. 10. 10. 10.]

Базовые статистики для arr1:
Среднее значение (mean): 3.0
Сумма всех элементов (sum): 15
Минимальное значение (min): 1
Максимальное значение (max): 5
